FROM node:22-alpine

WORKDIR /usr/src/metaverse

COPY ./package*.json ./
COPY ./turbo.json ./
COPY apps/backend/package.json apps/backend/package.json
COPY packages/db/package.json packages/db/package.json

RUN npm install

COPY ./packages/db ./packages/db
COPY ./apps/backend ./apps/backend

RUN npm run db:generate
RUN npm run build

EXPOSE 5000

CMD [ "npm", "run", "start:backend" ]

