FROM node:22-alpine

WORKDIR /usr/src/metaverse

COPY ./package*.json ./
COPY ./turbo.json ./
COPY ./apps/ws ./apps/ws
COPY ./packages/db ./packages/db

RUN npm install
RUN npm run db:generate
RUN npm run build

EXPOSE 8080

CMD [ "npm", "run", "start:ws" ]
