FROM node:22-alpine

WORKDIR /usr/src/metaverse

COPY ./package*.json ./
COPY ./turbo.json ./
COPY apps/ws/package.json apps/ws/package.json
COPY packages/db/package.json packages/db/package.json

RUN npm install

COPY ./apps/ws ./apps/ws
COPY ./packages/db ./packages/db

RUN npm run db:generate
RUN npm run build

EXPOSE 8080

CMD [ "npm", "run", "start:ws" ]
