FROM alpine:node:22

WORKDIR /usr/src/metaverse

COPY ./package*.json ./
COPY ./turbo.json ./
COPY apps/frontend/package.json apps/frontend/package.json
COPY packages/ui/package.json packages/ui/package.json

RUN npm install

COPY packages/ui packages/ui
COPY apps/frontend apps/frontend

RUN npm run build

EXPOSE 3000

CMD [ "npm", "run", "start:frontend" ]